# .tmux.conf
# prefix Ctrl + bで明示的に設定
set -g prefix C-b
unbind C-b
bind C-b send-prefix

# tmuxの設定をリロードするためのキーを設定
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# マウスを有効にする
#set -g mouse on

# ウィンドウのインデックスを表示する
set -g base-index 1
setw -g pane-base-index 1

# ステータスバーの設定
set -g status on
set -g status-interval 1
set -g status-justify centre
set -g status-left-length 30
set -g status-right-length 150
set -g status-left "#[fg=green]#S #[fg=yellow]#{?client_prefix,#[fg=red]PREFIX,}#[default]"
set -g status-right "#[fg=cyan]#{pane_current_path} #[fg=green]%Y-%m-%d %H:%M:%S"
set -g status-style bg=default,fg=default
setw -g window-status-current-format "#[fg=green,bold]#I:#W#F #[fg=yellow]#{pane_current_command}#[default]"
setw -g window-status-format "#I:#W#F"

# ペインの境界線の設定
set -g pane-border-format "#{pane_index}"
set -g pane-border-style "fg=green"
set -g pane-active-border-style "fg=green,bold"

# コマンドモードの設定
setw -g mode-style "fg=green,bold"

# ウィンドウの作成と削除
bind c new-window -c "#{pane_current_path}"
bind X confirm-before -p "kill-window #W? (y/n)" kill-window

# ペインの分割と移動
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# ペインの削除
bind x kill-pane

# ペインのリサイズ
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# コピーモードの設定。mouse mode onにしていたため、選択文字列を指定したキーボード操作を意図的に無効にしていたが、offにしたため、この設定も不要
#bind -T copy-mode-vi MouseDragEnd1Pane
bind P paste-buffer
# コピーモードをviスタイルにする
setw -g mode-keys vi

# vi風の選択・コピー操作
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle

# コピーモードに入るショートカット
bind [ copy-mode

# タブの切り替え(M→Alt) → prefixで切り替えているので不要
#bind-key -n M-l next-window
#bind-key -n M-h previous-window
# タブの移動 → prefixで切り替えているので不要
#bind-key -n M-k swap-window -t -1
#bind-key -n M-j swap-window -t +1

# タブの名前変更
bind-key C set-window-option automatic-rename off
bind-key , command-prompt -I "#W" "rename-window '%%'"


# コマンドの履歴を保存
set -g history-limit 10000

# ターミナルのタイトルを設定
set -g set-titles on
set -g set-titles-string "#T"

# ターミナルの色を設定
set -g default-terminal "screen-256color"
set -g terminal-overrides ",xterm-256color:Tc"

